FROM nginx:alpine

WORKDIR /home/buscamed

RUN apk add --no-cache certbot

COPY ./app/static app/static
COPY ./boot-nginx.sh boot-nginx.sh
RUN chmod +x boot-nginx.sh
COPY ./nginx_buscamed.conf /etc/nginx/conf.d/nginx_buscamed.conf
COPY ./logs logs
COPY certs/* /etc/letsencrypt/live/buscamed.com.br/

ENTRYPOINT [ "./boot-nginx.sh" ]
