"""Add frontend_total

Revision ID: 075df0e5bbd8
Revises: 31990393b672
Create Date: 2021-01-29 01:38:01.853057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075df0e5bbd8'
down_revision = '31990393b672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('frontend_total', sa.Numeric(precision=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'frontend_total')
    # ### end Alembic commands ###
