"""Add store_id to User model for staff purposes

Revision ID: 19c9c5105517
Revises: c8f6ed2a7024
Create Date: 2021-01-01 23:47:07.735652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c9c5105517'
down_revision = 'c8f6ed2a7024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'store_id')
    # ### end Alembic commands ###
