"""add canceled to order

Revision ID: 31990393b672
Revises: db3b724303df
Create Date: 2021-01-27 00:09:07.285804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31990393b672'
down_revision = 'db3b724303df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('canceled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'canceled')
    # ### end Alembic commands ###
