"""add member since

Revision ID: 31d8f37a2e74
Revises: 19c9c5105517
Create Date: 2021-01-06 18:08:31.806624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d8f37a2e74'
down_revision = '19c9c5105517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'member_since')
    # ### end Alembic commands ###
