"""add description, bula, active_principle, ms_registry to Item

Revision ID: 48005c3d49e7
Revises: e0688a829fc9
Create Date: 2021-01-16 14:45:02.634248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48005c3d49e7'
down_revision = 'e0688a829fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('active_principle', sa.String(length=64), nullable=True))
    op.add_column('item', sa.Column('bula', sa.String(length=256), nullable=True))
    op.add_column('item', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('item', sa.Column('ms_registry', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'ms_registry')
    op.drop_column('item', 'description')
    op.drop_column('item', 'bula')
    op.drop_column('item', 'active_principle')
    # ### end Alembic commands ###
