"""Add timestamp to Item

Revision ID: 54585a88e1ba
Revises: 8ed211d700f4
Create Date: 2020-12-17 16:04:39.463212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54585a88e1ba'
down_revision = '8ed211d700f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'timestamp')
    # ### end Alembic commands ###
