"""change address

Revision ID: 54f7dc472d9e
Revises: 075df0e5bbd8
Create Date: 2021-01-29 18:45:59.032501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f7dc472d9e'
down_revision = '075df0e5bbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bairro', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('cep', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('logradouro', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('municipio', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('uf', sa.String(length=2), nullable=True))
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'uf')
    op.drop_column('user', 'municipio')
    op.drop_column('user', 'logradouro')
    op.drop_column('user', 'cep')
    op.drop_column('user', 'bairro')
    # ### end Alembic commands ###
