"""Add column to store

Revision ID: 59ac87e00a58
Revises: 607f62803f7f
Create Date: 2020-12-17 16:48:46.217458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ac87e00a58'
down_revision = '607f62803f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_ean_store_uc', 'item', ['ean', 'store_id'])
    op.create_unique_constraint('_sku_store_uc', 'item', ['sku', 'store_id'])
    op.add_column('store', sa.Column('has_delivery', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'has_delivery')
    op.drop_constraint('_sku_store_uc', 'item', type_='unique')
    op.drop_constraint('_ean_store_uc', 'item', type_='unique')
    # ### end Alembic commands ###
