"""change names

Revision ID: 6891bb640775
Revises: 799fa66d6c53
Create Date: 2021-02-02 00:23:31.391726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6891bb640775'
down_revision = '799fa66d6c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('payment', 'payment_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('payment_method', 'payment')
    # ### end Alembic commands ###
