"""rename column

Revision ID: 789feb368214
Revises: 993a0e151b56
Create Date: 2021-02-09 15:02:06.263658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789feb368214'
down_revision = '993a0e151b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('requires_prescription', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('item', 'requires_precription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('requires_precription', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('item', 'requires_prescription')
    # ### end Alembic commands ###
