"""numeric fix + not nullable payment

Revision ID: 7e509160c070
Revises: b7d6a5645b3f
Create Date: 2021-01-31 19:37:33.027246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e509160c070'
down_revision = 'b7d6a5645b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'producer',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=90),
               existing_nullable=True)
    op.alter_column('order', 'cash_value',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('order', 'delivery_fee',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('order', 'frontend_total',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('order', 'payment_method',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'total',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.String(length=19),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=19),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.alter_column('order', 'total',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.alter_column('order', 'payment_method',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'frontend_total',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.alter_column('order', 'delivery_fee',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.alter_column('order', 'cash_value',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
    op.alter_column('item', 'producer',
               existing_type=sa.String(length=90),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
