"""farmasegura waitline remove phone

Revision ID: 97776bb2e947
Revises: e3e4ac20c52d
Create Date: 2021-04-20 17:13:24.386496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97776bb2e947'
down_revision = 'e3e4ac20c52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farma_segura_wait_line', 'phone',
               existing_type=sa.VARCHAR(length=19),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farma_segura_wait_line', 'phone',
               existing_type=sa.VARCHAR(length=19),
               nullable=False)
    # ### end Alembic commands ###
