"""add requires_prescription

Revision ID: 993a0e151b56
Revises: 6891bb640775
Create Date: 2021-02-08 00:30:30.230801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993a0e151b56'
down_revision = '6891bb640775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('requires_precription', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'requires_precription')
    # ### end Alembic commands ###
