"""add is_active to store and item + rename brand to producer

Revision ID: 9c334bdf5ea8
Revises: da2a936aea65
Create Date: 2020-12-20 01:35:38.122428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c334bdf5ea8'
down_revision = 'da2a936aea65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_active', sa.Boolean(),
                                    server_default='true', nullable=False))

    # op.add_column('item', sa.Column('producer', sa.String(length=64), nullable=True))
    # op.drop_column('item', 'brand')
    op.alter_column('item', 'brand', new_column_name='producer')

    op.add_column('store', sa.Column('is_active', sa.Boolean(),
                                     server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'is_active')

    # op.add_column('item', sa.Column('brand', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # op.drop_column('item', 'producer')
    op.alter_column('item', 'producer', new_column_name='brand')

    op.drop_column('item', 'is_active')
    # ### end Alembic commands ###
