"""Add orders + click count

Revision ID: c9e0fe94b252
Revises: 48005c3d49e7
Create Date: 2021-01-18 12:52:22.139364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e0fe94b252'
down_revision = '48005c3d49e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_detail_click',
    sa.Column('ean', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ean')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('placed_timestamp', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Integer(), nullable=True),
    sa.Column('cash_value', sa.Numeric(precision=2), nullable=True),
    sa.Column('delivery_method', sa.Integer(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=2), nullable=False),
    sa.Column('assigned_deliveryman', sa.Boolean(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_delivered_timestamp'), 'order', ['delivered_timestamp'], unique=False)
    op.create_index(op.f('ix_order_placed_timestamp'), 'order', ['placed_timestamp'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_item_id'), 'order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('store', sa.Column('buscamed_delivery', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('store', sa.Column('own_delivery', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('store', 'has_delivery')
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    op.add_column('store', sa.Column('has_delivery', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('store', 'own_delivery')
    op.drop_column('store', 'buscamed_delivery')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_placed_timestamp'), table_name='order')
    op.drop_index(op.f('ix_order_delivered_timestamp'), table_name='order')
    op.drop_table('order')
    op.drop_table('product_detail_click')
    # ### end Alembic commands ###
