"""Add radius to user

Revision ID: db3b724303df
Revises: 9aa8b8cbaad0
Create Date: 2021-01-26 01:51:25.641500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3b724303df'
down_revision = '9aa8b8cbaad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('radius', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'radius')
    # ### end Alembic commands ###
