"""price to decimal

Revision ID: e7e4519094c2
Revises: 789feb368214
Create Date: 2021-02-15 21:36:05.946631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7e4519094c2'
down_revision = '789feb368214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('item', 'promotion_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'promotion_price',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('item', 'price',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
